Single-multiple.md update
babelfish-for-postgresql/babelfish_project_website pull request #173
Opened 2022-02-01 14:57 UTC by susanmdouglas-aws

### Description
Edited single-multiple.md file to improve and clarify content, voice, tense, and grammar.
 
### Issues Resolved
Makes the content more usable.

### Check List
- [x ] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2022-02-01 15:55 UTC, rcv-aws commented on _installation/single-multiple.md
> +When you create a Babelfish cluster, you choose between using a single T-SQL database or multiple T-SQL databases together. Your choice will affects how the names of T-SQL schemas inside the Babelfis
"single T-SQL database" ==> "single migrated T-SQL user database"
"multiple T-SQL databases together" ==> "multiple migrated T-SQL user databases together"

2022-02-01 15:55 UTC, rcv-aws commented on _installation/single-multiple.md
>  your user databases and clients.
clients ==> client applications

2022-02-01 15:56 UTC, rcv-aws commented on _installation/single-multiple.md
>    PostgreSQL, your SQL code will require fewer modifications.
will ==> may

2022-02-01 15:57 UTC, rcv-aws requested changes
added various comments

2022-02-01 17:05 UTC, susanmdouglas-aws commented on _installation/single-multiple.md
> +When you create a Babelfish cluster, you choose between using a single T-SQL database or multiple T-SQL databases together. Your choice will affects how the names of T-SQL schemas inside the Babelfis
Updated, thanks!

2022-02-01 17:06 UTC, susanmdouglas-aws commented on _installation/single-multiple.md
>  your user databases and clients.
Updated... thanks!

2022-02-01 17:07 UTC, susanmdouglas-aws commented on _installation/single-multiple.md
>    PostgreSQL, your SQL code will require fewer modifications.
Updated, thanks!

2022-02-01 17:18 UTC, susanmdouglas-aws commented
I've updated the file and checked in the updates... thanks!

2022-02-02 17:05 UTC, 3manuek submitted a review, later dismissed

2022-02-03 19:13 UTC, rcv-aws commented on _installation/single-multiple.md
> +When you create a Babelfish cluster, you choose between using a single migrated T-SQL user database or multiple migrated T-SQL user databases together. Your choice will affects how the names of T-SQL
affects ==> affect

2022-02-03 19:19 UTC, rcv-aws approved these changes
just a grammar error, otherwise OK

2022-02-03 20:12 UTC, susanmdouglas-aws commented on _installation/single-multiple.md
> +When you create a Babelfish cluster, you choose between using a single migrated T-SQL user database or multiple migrated T-SQL user databases together. Your choice will affects how the names of T-SQL
Thank you - fixed!

2022-02-03 20:34 UTC, rcv-aws approved these changes

2022-02-04 11:04 UTC, 3manuek approved these changes

2022-02-04 11:04 UTC, merged