Updated command-line.md
babelfish-for-postgresql/babelfish_project_website pull request #185
Opened 2022-03-08 17:00 UTC by susanmdouglas-aws

Improved consistency of grammar and added note (per Simon) about connecting on SSMS.

Signed-off-by: susanmdouglas <susandou@amazon.com>

### Description
This update improves the grammar in the command-line.md file, and adds warning from Simon about connecting on SSMS.
 
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ x] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2022-03-08 22:48 UTC, rcv-aws requested changes
added a note about the -d flag on sqlcmd

2022-03-09 11:48 UTC, susanmdouglas-aws commented on _usage/command-line.md
> +- `-d` is the database to which you are connecting.
I've updated the description of -d:

-d` is the database to which you are connecting. This value is optional; if omitted, the client will 
connect to the `master` database.

2022-03-09 11:48 UTC, susanmdouglas-aws commented on _usage/command-line.md
> +- `-d` is the database to which you are connecting.
Thanks!

2022-03-09 13:16 UTC, rcv-aws approved these changes

2022-03-10 16:05 UTC, 3manuek approved these changes

2022-03-10 16:11 UTC, merged