DO NOT MERGE UNTIL Babelfish release 1.4.1 release day
babelfish-for-postgresql/babelfish_project_website pull request #251
Opened 2022-12-19 20:59 UTC by susanmdouglas-aws

This PR contains the release notes for version 1.4.1.

Signed-off-by: susanmdouglas <susandou@amazon.com>

### Description
This PR contains the release notes for version 1.4.1.

 
### Issues Resolved
This PR contains the release notes for version 1.4.1.

### Check List
- [x] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2022-12-20 13:37 UTC, shardgupta approved these changes

2022-12-20 16:41 UTC, susanmdouglas-aws commented on _includes/releases/babelfish-1.4.1.md
> +
I've added a line for extension version into the header.

2022-12-21 13:52 UTC, shardgupta approved these changes

2022-12-21 14:12 UTC, rishabhtanwar29 submitted a review, later dismissed

2022-12-21 15:41 UTC, kuntalghosh approved these changes

2022-12-21 15:49 UTC, kuntalghosh requested changes

2022-12-21 15:49 UTC, kuntalghosh commented on _includes/releases/babelfish-1.4.1.md
> +
This should be minor version upgrade from 13.4 to 13.8.

2022-12-21 16:26 UTC, susanmdouglas-aws commented on _includes/releases/babelfish-1.4.1.md
> +
Updated...

2022-12-21 16:36 UTC, kuntalghosh approved these changes

2022-12-21 16:46 UTC, shardgupta approved these changes

2022-12-21 16:53 UTC, rishabhtanwar29 approved these changes

2022-12-21 17:07 UTC, Deepesh125 approved these changes

2022-12-21 17:13 UTC, merged