DO NOT MERGE UNTIL Babelfish Release 1.3.3
babelfish-for-postgresql/babelfish_project_website pull request #254
Opened 2022-12-20 19:23 UTC by susanmdouglas-aws

Initial check in of release notes for 1.3.3

Signed-off-by: susanmdouglas <susandou@amazon.com>

### Description
Initial check in of release notes for 1.3.3

 
### Issues Resolved
Initial check in of release notes for 1.3.3

### Check List
- [x] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2022-12-21 15:27 UTC, shardgupta approved these changes

2022-12-21 15:48 UTC, kuntalghosh requested changes

2022-12-21 15:48 UTC, kuntalghosh commented on _includes/releases/babelfish-1.3.3.md
> +- Fixes an issue that prevents a successful minor version upgrade from Babelfish PostgreSQL 13.4 to PostgreSQL 13.5.
This should be minor version upgrade from 13.4 to 13.7.

2022-12-22 15:48 UTC, shardgupta approved these changes

2022-12-22 16:51 UTC, kuntalghosh approved these changes

2022-12-22 16:55 UTC, merged