Change "lincense" -> "license" and add an article
babelfish-for-postgresql/babelfish_project_website pull request #77
Opened 2021-11-03 12:47 UTC by laurenz

2021-11-03 13:47 UTC, susanmdouglas-aws approved these changes
It looks good to me...

2021-11-03 15:19 UTC, nasbyj submitted a review, later dismissed

2021-11-03 15:19 UTC, 3manuek submitted a review, later dismissed

2021-11-03 22:14 UTC, rcv-aws commented on _docs/contributing.md
>  Babelfish is available as Open Source software and can be downloaded from Github
The product name is 'Babelfish for PostgreSQL'

2021-11-03 22:15 UTC, rcv-aws requested changes
use correct product name

2021-11-04 11:19 UTC, laurenz commented
Thanks for the review. I pushed a commit that is more specific about this.

2021-11-10 19:04 UTC, 3manuek approved these changes

2021-11-11 11:35 UTC, laurenz commented
Please approve and merge this.

2021-11-11 11:39 UTC, rcv-aws approved these changes

2021-11-11 12:56 UTC, merged